// Date: 4/24/2014 1:14:43 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package emd24.rpgmod.combatitems;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class HolyHandGrenadeModel extends ModelBase
{
  //fields
    ModelRenderer inner;
    ModelRenderer horz1;
    ModelRenderer crossv;
    ModelRenderer horz2;
    ModelRenderer crossh;
    ModelRenderer Shape2;
  
  public HolyHandGrenadeModel()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      inner = new ModelRenderer(this, 0, 0);
      inner.addBox(0F, 0F, 0F, 5, 5, 5);
      inner.setRotationPoint(0F, 0F, 0F);
      inner.setTextureSize(64, 32);
      inner.mirror = true;
      setRotation(inner, 0F, 0F, 0F);
      horz1 = new ModelRenderer(this, 0, 10);
      horz1.addBox(-1F, 1F, 1F, 7, 3, 3);
      horz1.setRotationPoint(0F, 0F, 0F);
      horz1.setTextureSize(64, 32);
      horz1.mirror = true;
      setRotation(horz1, 0F, 0F, 0F);
      crossv = new ModelRenderer(this, 20, 10);
      crossv.addBox(2F, -4F, 2F, 1, 3, 1);
      crossv.setRotationPoint(0F, 0F, 0F);
      crossv.setTextureSize(64, 32);
      crossv.mirror = true;
      setRotation(crossv, 0F, 0F, 0F);
      horz2 = new ModelRenderer(this, 0, 16);
      horz2.addBox(1F, 1F, -1F, 3, 3, 7);
      horz2.setRotationPoint(0F, 0F, 0F);
      horz2.setTextureSize(64, 32);
      horz2.mirror = true;
      setRotation(horz2, 0F, 0F, 0F);
      crossh = new ModelRenderer(this, 20, 14);
      crossh.addBox(2F, -3F, 1F, 1, 1, 3);
      crossh.setRotationPoint(0F, 0F, 0F);
      crossh.setTextureSize(64, 32);
      crossh.mirror = true;
      setRotation(crossh, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 20, 0);
      Shape2.addBox(1F, -1F, 1F, 3, 7, 3);
      Shape2.setRotationPoint(0F, 0F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    inner.render(f5);
    horz1.render(f5);
    crossv.render(f5);
    horz2.render(f5);
    crossh.render(f5);
    Shape2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
